### ISSUE TITLE
Can't parse value "(props) => (props.isHover ? 'block' : 'none')"

### ISSUE THREAD

**Issue by Avivhdr** [csstree/stylelint-validator#37]
I'm using ReactJS and Material-UI.

I'm styling my components using `makeStyles` which implements css-in-js.

The validator gives an error for this type of value:
```javascript
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles(() => ({
  actions: {
    display: (props) => (props.isHover ? 'block' : 'none'),
  },
}));
```

The error:
```
35:4  ✖  Can't parse value "(props) => (props.isHover ? 'block' : 'none')"       csstree/validator
```

What can be done in order for the validator to recognize the function given as a value and evaluate its return value (`block`/`none`)?

**Comment by lahmatiy** [comment]
The validator is designed to check CSS syntax only. Css-in-js is not supported and I suppose will never be, since it's require to parse/evaluate JavaScript to get a value (or values) which be used for a declaration. That's incredible hard task. Your example is quite simple, but there are many ways to do the same which would not work because a little bit different. So I won't even try (I have tried doing similar things in the past, so I understand the complexity and impracticability).
However, if you will be able to extract a declaration name and its values somehow, you can make your own validator using csstree for a validation values.

**Comment by Avivhdr** [comment]
> However, if you will be able to extract a declaration name and its values somehow, you can make your own validator using csstree for a validation values.

I'm not sure that I got what you meant with this sentence.

I thought about using regex to identify that the declared value is a function, and if it is, the validation would be positive (even though we still don't know what the value would be.)

I also see now that `styled-components` have a [linting plugin](https://styled-components.com/docs/tooling#stylelint) and I wonder how it works. There are many `css-in-js` libraries so there should be a solution that would fit all of them.

**Comment by lahmatiy** [comment]
In case you want to ignore such values, you could use `ignoreValue` option (see description in readme)

**Comment by Avivhdr** [comment]
@lahmatiy Great 🙏
